name: 🐛 Bug Report
description: Create a report to help us improve Orleans.StateMachineES
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Orleans.StateMachineES are you running?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: dropdown
    id: orleans-version
    attributes:
      label: Orleans Version
      description: What version of Microsoft Orleans are you using?
      options:
        - Orleans 9.1.2
        - Orleans 9.1.1
        - Orleans 9.1.0
        - Orleans 9.0.x
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Core StateMachineGrain
        - Event Sourcing
        - Hierarchical States
        - Timers & Reminders
        - Saga Orchestration
        - Distributed Tracing
        - Health Checks & Monitoring
        - Visualization
        - Versioning & Migration
        - State Machine Composition
        - Roslyn Source Generator
        - Orthogonal Regions
        - Examples
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        A clear and concise description of what the bug is.
        
        **Tip**: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: "Describe the issue..."
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "Describe what you expected..."
    validations:
      required: true

  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to Reproduce
      description: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: |
        If applicable, add a minimal code sample that reproduces the issue.
        
        **Tip**: Use code blocks (```) for better formatting.
      render: csharp
      placeholder: |
        ```csharp
        // Your code here
        ```

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide your environment details:
      placeholder: |
        - OS: [e.g., Windows 11, Ubuntu 22.04, macOS 13]
        - .NET Version: [e.g., .NET 9.0]
        - IDE: [e.g., Visual Studio 2022, Rider, VS Code]
        - Container: [e.g., Docker, Kubernetes, None]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Before submitting, please check the following:
      options:
        - label: I have searched for existing issues that might be related to this bug
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I have tested this with the latest version of Orleans.StateMachineES
          required: false